# Generated by Django 5.0.7 on 2024-07-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cooking_time', models.IntegerField(help_text='Cooking time in minutes')),
                ('country', models.CharField(max_length=100)),
                ('ingredients', models.JSONField()),
                ('instructions', models.JSONField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='recipes/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
